version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashcards
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

  server:
    build: .
    ports:
      - 8000:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/flashcards
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    container_name: flashcards-api
    restart: unless-stopped
    image: flashcards-api:latest
    depends_on:
      - db

volumes:
  db: {}